// console.log("Jai Sai Master");
// console.log("Jai Bapuji Maharaj");

// var a = [2, 3, 6, 8, 2];

// c = 0;
// for (i = 0; i < a.length; i++) {
//   if (a[i] < a[i + 1]) {
//     c = c + 1;
//   }
// }
// if (c == a.length - 1) {
//   console.log("true");
// } else {
//   console.log("false");
// }

// var a = 5721736;

// b = a.toString().split("");
// num = "";
// for (i = 0; i < a.length; i++) {
//   num = Number(a[i]);
// }
// console.log(num);
// // console.log(c);

// var a = [213, 687, 12, 10, 51];
// // op= a=[312, 786, 21,01,15]

// empty = [];
// for (i = 0; i < a.length; i++) {
//   num = String(a[i]).split("");
//   console.log(num);
//   b = num.reverse().join("");
//   console.log(b);
//   empty.push(Number(b));
// }

// console.log(empty);

// var arr = ["BharGav", "vAmsI", "ChaiTanYa"];

// let Caps = [];
// let Small = [];
// for (var i = 0; i < arr.length; i++) {
//   for (var j = 0; j < arr[i].length; j++) {
//     if (arr[i][j] == arr[i][j].toUpperCase()) {
//       console.log(arr[i][j]);
//       // Caps += arr[i][j];
//       Caps.push(arr[i][j]);
//     } else {
//       console.log(arr[i][j]);
//       Small.push(arr[i][j]);
//     }
//   }
// }

// console.log(Caps);
// console.log(Small);

// var arr = ["BharGav", "vAmsI", "ChaiTanYa"];

// let result = arr.map((word) => {
//   return word
//     .split("")
//     .map((char, index) => {
//       return index === 0 ? char.toUpperCase() : char.toLowerCase();
//     })
//     .join("");
// });

// console.log(result);

// console.log(Caps + Small);
// var a= ["BhanU", "PraKaSH"]

// for(){

// }
