console.log("-- DATE: 28/12/23  DAY: THURSDAY--");

// debugger;
//  using "FOR LOOP "
var n = 3;
var c = 0;
for (i = 2; i < n; i++) {
  if (n % i == 0) {
    c++;
    console.log(`${n} is not a Prime number`);
    break;
  }
}

if (c == 0) {
  console.log(`${n} is a Prime number`);
} 

// using WHLE LOOP

// a = +prompt("enter a number");

// debugger;
/* a = 4;
c = 0;
 i = 2;
while (i < a) {
  if (a % i == 0) {
    console.log("not a prime");
    c++;
    // break;
  }
  i++;
}

if (c == 0) {
  console.log(" it is prime");
} */

//  -----------------------------------------------------------------------------------------------------------------------------------------------------

//  Using do-while loop

// b = 7;
// c = 0;

// i = 2;

// do {

// } while (i < b);

// a = 10;
// console.log(a);
// // let  a = 10;
// console.log(a);

// let a = 10;
// a = 10;
