// DATE: 29/12/23                               DAY: FRIDAY

console.log("--- DATE: 29/12/23    DAY: FRIDAY  ---");

//-- PRINTING A NUMBER IS EVEN OR ODD-- //

// debugger;
// var n = +prompt("Enter a number"); // or

// var n = Number(prompt("Enter a number"));

// switch (n % 10) {
//   case 0:
//     console.log("Even number");
//     break;

//   case 1:
//     console.log("Odd number");
// }

// --CHECKING WHETHER "n"  ENDS WITH ZERO OR NOT-- //

// using IF STATEMENT

// let a = 1450;
// if (a % 10 == 0) {
//   console.log(`${a} ends with Zero `);
// } else {
//   console.log(`${a} is not ends with Zero`);
// }

// using FOR LOOP //

// for (i = 0; i < 50; i++) {
//   if (i % 10 == 0) {
//     console.log(`${i} ends with Zero `);
//   } else {
//     console.log(`${i} is not ends with Zero`);
//   }
// }

// using SWITCH CASE
// var n = +prompt("Enter a Number");

// switch (n % 10) {
//   case 0:
//     console.log("number end's with zero");
//     break;

//   default:
//     console.log("number doesn't end's with zero");
// }

//  -------------------------------------------------------------------------------------------------------------------------------------------------------
