console.log("Jai Sai master");
console.log("Jai Bapuji maharaj");

console.log("---DATE: 30/12/23  DAY:SATURDAY  ---");

// Displaying the numbers which are ends with zero in Array usig for loop
// a = [2, 70, 83, 90, 13];

// for (i = 0; i < a.length; i++) {
//   if (a[i] % 10 == 0) {
//     console.log(a[i]);
//   }
// }

// Displaying the count of  numbers which are ends with zero  Array using for loop

// a = [2, 70, 83, 90, 13];
// count = 0;
// for (i = 0; i < a.length; i++) {
//   if (a[i] % 10 == 0) {
//     count++;
//   }
// }
// console.log(count);

// Displaying the Sum of  numbers which are ends with zero  Array using for loop

// a = [2, 70, 83, 90, 13];
// sum = 0;
// for (i = 0; i < a.length; i++) {
//   if (a[i] % 10 == 0) {
//     sum += a[i];
//   }
// }
// console.log(sum);

// Displaying the Sum of  numbers which are not ends with zero in Arrray using for loop
// a = [2, 70, 83, 90, 13];
// sum = 0;
// for (i = 0; i < a.length; i++) {
//   if (a[i] % 10 !== 0) {
//     sum += a[i];
//   }
// }
// console.log(sum);
// -------------------------------------------------------------------------------------------------------------------------------------------------------

// using "FOR IN  LOOP" Finding Numbers ends with zero
// a = [2, 5, 450, 850, 103];
// count = 0;
// for (i in a) {
//   if (a[i] % 10 == 0) {
//     count++;
//   }
// }
// console.log(count);

// using "FOR OF LOOP" Finding Numbers ends with zero

// using "FOR OF"
// a = [2, 5, 450, 850, 103];
// count = 0;
// for (i of a) {
//   if (i % 10 == 0) {
//     count++;
//   }
// }
// console.log(count);

//  Find outing Even  numbers  in an Array using  "FOR IN LOOP"

// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i in a) {
//   if (a[i] % 2 == 0) {
//     console.log(a[i]);
//   }
// }

//  Find outing odd  numbers  in an Array using  "FOR IN LOOP"

// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i in a) {
//   if (a[i] % 2 !== 0) {
//     console.log(a[i]);
//   }
// }

//  Find outing Even  numbers  in an Array using  "FOR OF LOOP"

// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i of a) {
//   if (i % 2 == 0) {
//     console.log(i);
//   }
// }

//  Find outing odd  numbers  in an Array using  " FOR OF LOOP"

// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i of a) {
//   if (i % 2 !== 0) {
//     console.log(i);
//   }
// }

//  Find outing Sum of Even  numbers  in an Array using  "FOR IN  LOOP"

// sum = 0;
// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i in a) {
//   if (a[i] % 2 == 0) {
//     sum += a[i];
//   }
// }

// console.log(sum);

//  Find outing Sum of Odd numbers  in an Array using  "FOR IN LOOP "
// sum = 0;
// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i in a) {
//   if (a[i] % 2 !== 0) {
//     sum += a[i];
//   }
// }

// console.log(sum);

//  Find outing Sum of Even numbers  in an Array using  "FOR OF LOOP"
// sum = 0;
// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i of a) {
//   if (i % 2 == 0) {
//     sum += i;
//   }
// }

// console.log(sum);

//  Find outing Sum of Odd numbers  in an Array using  "FOR OF LOOP"
// sum = 0;
// a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
// for (i of a) {
//   if (i % 2 !== 0) {
//     sum += i;
//   }
// }

// console.log(sum);

// debugger;

// var a;

// a = 12;

// a = 10;

// var a;
// console.log(a);
