console.log("Jai Sai master");
console.log("Jai Bapuji Maharaj");

// printing a factorial of a number
/* let f = "1";
function factorial(n) {
  for (i = 6; i > 0; i--) {
    f *= i;
  }
}

factorial(6);
console.log(f); */
// priting fibanocci series of numbers

/*var n = 10;
var a = 0;
var b = 1;
var temp;
console.log(a);
console.log(b);
sum = 0;
for (var i = 0; i < 10; i++) {
  if (a % 2 == 0) {
    console.log(a);
    sum += a;
  }
  temp = a + b;
  a = b;
  b = temp;
}

console.log(sum); */


