console.log("Jai Sai Master");
console.log("Jai Bapuji Maharaj");

// priting fibanocci series of numbers

/*var n = 10;
var a = 0;
var b = 1;
var temp;
console.log(a);
console.log(b);
sum = 0;
for (var i = 0; i < 10; i++) {
  if (a % 2 == 0) {
    console.log(a);
    sum += a;
  }
  temp = a + b;
  a = b;
  b = temp;
}

console.log(sum); */

//--------------------

/*var n = 10;
var a = 0;
var b = 1;
var temp;
console.log(a);
console.log(b);
sum = 0;
for (var i = 0; i < 10; i++) {
  if (a % 2 !== 0) {
    console.log(a);
    sum += a;
  }
  temp = a + b;
  a = b;
  b = temp;
}

console.log(sum); */
//------------------------------------
/*var n = 5;
var a = 0;
var b = 1;
var temp;
// console.log(a);
// console.log(b);
var i = 1;
while (i <= n + 2) {
  console.log(a);
  tempt = b + a;
  a = b;
  b = tempt;
  if (a > n) {
    break;
  }
  i++;
} */

/*var a = 0;
var b = 1;
var temp;
var n = 5;

for (var i = 1; a <= n; i++) {
  console.log(a);
  temp = a + b;
  a = b;
  b = temp;
} */

//---------------------------------------
// var n = 10;
// var a = 0;
// var b = 1;
// var temp;
// console.log(a);
// console.log(b);
// for (var i = 0; i < n; i++) {
//   temp = a + b;
//   console.log(temp);
//   a = b;
//   b = temp;
// }

// printing the numbers upto given number
// var a = 0;
// var b = 1;
// var temp;
// var n = 5;
// for (var i = 0; a <= n; i++) {
//   console.log(a);
//   temp = a + b;
//   a = b;
//   b = temp;
// }
